# Generated by Django 4.2.1 on 2023-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('info', models.TextField(verbose_name='Информация')),
                ('location', models.CharField(max_length=255, verbose_name='Место обитание')),
                ('photo', models.ImageField(upload_to='plants_photo', verbose_name='Фото')),
            ],
        ),
    ]
