# Generated by Django 4.2.1 on 2023-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name': 'Растение', 'verbose_name_plural': 'Растения'},
        ),
    ]
