# Generated by Django 4.2.1 on 2023-05-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='location',
        ),
    ]
