# Generated by Django 4.2.1 on 2023-05-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Посетителя',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.AlterField(
            model_name='time',
            name='number_in_the_group',
            field=models.PositiveIntegerField(default=50, verbose_name='Количество в группе'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(choices=[('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('00:00', '00:00'), ('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00'), ('05:30', '05:30')], max_length=5, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='time',
            name='total',
            field=models.PositiveIntegerField(default=1200, verbose_name='Общее количество'),
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='visitor',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.time', verbose_name='Время'),
        ),
    ]
