# Generated by Django 4.2.1 on 2023-05-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_visitor_alter_time_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=255, verbose_name='Название')),
                ('organizer_name', models.CharField(max_length=100, verbose_name='Имя организатора')),
                ('contact', models.CharField(max_length=13, verbose_name='Номер организатора')),
                ('date', models.DateField(verbose_name='Дата(-ы) проведения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('anons', models.TextField(verbose_name='Анонс')),
                ('advertising', models.TextField(verbose_name='Реклама')),
                ('total', models.PositiveIntegerField(default=1200, verbose_name='Общее количество')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.RemoveField(
            model_name='time',
            name='total',
        ),
        migrations.AlterField(
            model_name='time',
            name='number_in_the_group',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество в группе'),
        ),
        migrations.AddField(
            model_name='time',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.event'),
            preserve_default=False,
        ),
    ]
