# Generated by Django 4.2.1 on 2023-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_event_remove_time_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_name',
        ),
    ]
