# Generated by Django 4.2.1 on 2023-05-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_event_options_alter_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='advertising',
        ),
    ]
